---
title: "Classification"
author: "Filip Binkiewicz, Wojtek Szymański"
date: "14 November 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Choosing relevant genes
First, we choose the genes which appear to be relevant. To do so,
we use Spearman's coefficient and FDR correction.
```{r choosing genes, warning=FALSE}
setwd('/home/filip/MIM/Matematyka/StatystykaII/Statistics-II/glioblastoma/data')
load("GlioblastomaWide.rda")

genes <- GlioblastomaWide
alpha <- 0.2
died <- genes[[4]]
relevant_genes <- genes[1]

cluster_pval <- chisq.test(genes[2], died)$p.value
  if (cluster_pval < alpha) 
    {
      relevant_genes[[names(genes)[[2]]]] <- genes[[2]]
    }
age_pval <- chisq.test(genes[3], died)$p.value
  if (age_pval < alpha) 
    {
      relevant_genes[[names(genes)[[3]]]] <- genes[[3]]
    }
relevant_genes[[names(genes)[[4]]]] <- died

new_genes <- genes[1:4]
gene_pval <- NULL
  for (i in 5:length(genes)) 
  {
    if (length(which(is.na(genes[i]))) < 5) 
    {
      gene_pval <- c(gene_pval, cor.test(as.numeric(ifelse(died == "alive",1,0)), genes[[i]], method = "spearman")$p.value)
      new_genes[[names(genes)[[i]]]] <- genes[[i]]
    }
  }
correct_pval <- p.adjust(gene_pval, method = "fdr")
  for (i in 5:length(new_genes))
  {
    if(correct_pval[i-4]<alpha)
    {
      relevant_genes[[names(new_genes)[[i]]]] <- new_genes[[i]]  
    }
  }
length(relevant_genes) # these genes were chosen on the whole sample

alive_smp <- sample(new_genes$sampleID[new_genes$death1y=="alive"], 35)
dead_smp <- sample(new_genes$sampleID[new_genes$death1y=="dead"], 35)

Dane_alive<-new_genes[new_genes$sampleID %in% alive_smp,]
Dane_dead<-new_genes[new_genes$sampleID %in% dead_smp,]

training_genes<-rbind(Dane_alive, Dane_dead)

test_died <- training_genes[[4]]
training_relevant_genes <- training_genes[1]

test_cluster_pval <- chisq.test(training_genes[2], test_died)$p.value
if (test_cluster_pval < alpha) 
{
  training_relevant_genes[[names(new_genes)[[2]]]] <- training_genes[[2]]
}
test_age_pval <- chisq.test(training_genes[3], test_died)$p.value
if (test_age_pval < alpha) 
{
  training_relevant_genes[[names(new_genes)[[3]]]] <- training_genes[[3]]
}
training_relevant_genes[[names(new_genes)[[4]]]] <- test_died

test_gene_pval <- NULL
for (i in 5:length(training_genes))
{
  test_gene_pval <- c(test_gene_pval, cor.test(as.numeric(ifelse(test_died == "alive",1,0)), training_genes[[i]], method = "spearman")$p.value)
}
test_correct_pval <- p.adjust(test_gene_pval, method = "fdr")

for (i in 5:length(training_genes))
{
  if(test_correct_pval[i-4]<alpha)
  {
    training_relevant_genes[[names(new_genes)[[i]]]] <- training_genes[[i]]  
  }
}

# length(relevant_genes)

length(training_relevant_genes)

# length(intersect(names(relevant_genes), names(training_relevant_genes)))

training_data <- training_relevant_genes; training_data$sampleID <- NULL
training_rows <- as.numeric(rownames(training_relevant_genes))
testing_data <- genes[-training_rows, names(training_data)]

```

## Prediction
### Decision tree
```{r decision_tree}
library(rpart)
library(rpart.plot)

decision.tree <- rpart(death1y ~ ., data=training_data)
prp(decision.tree)  # pretty print the tree generated by rpart
```

## Prediction quality analysis
### ROC Curve
```{r ROCR}
library(ROCR)
pred <- prediction(predict(decision.tree, type = "prob")[, 2], training_data$death1y)
plot(performance(pred, "tpr", "fpr"))
abline(0, 1, lty = 2)
```